source 'https://rubygems.org'

gem 'sass', '~> 3.3'
gem 'bourbon', '~> 4.0'
gem 'middleman-core', '~>3.2.2'
gem 'middleman-livereload', '~> 3.3.4'
gem 'rack-rewrite', '~> 1.5.0'
gem 'scss-lint', '~> 0.26.2'
gem 'hamlbars', '~> 2.1.1'
gem 'wdm', '~> 0.1.0', :platforms => [:mswin, :mingw]